name: DayTime 자동화

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 내려받기
        uses: actions/checkout@v4

      - name: Node.js 18 세팅
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 의존성 설치
        run: npm install

      - name: 테스트 실행
        run: npm test

      - name: 빌드 실행
        run: npm run build

      - name: Build artifact 업로드
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: GitHub Pages에 배포
        uses: actions/deploy-pages@v4
